### ISSUE TITLE
SaaS Stats

### ISSUE THREAD

**Issue by cmsalmeida** [it-projects-llc/odoo-saas-tools#100]
### Suggested statistics:
- [ ] Count users: users_len (existent)
- [ ] File storage (MB): file_storage (existent)
- [ ] DB storage (MB): db_storage (existent)
- [ ] Data in: input_data_transfer (we are using nginx maybe better to get from it, but check alternatives)
- [ ] Data out: output_data_transfer
- [ ] DB requests: db_requests
- [ ] Installed modules: modules_number, number of installed modules
### Gather statistics:
- This statistics should be created by each client, and gathered in main saas database:
  - [x] periodically by scheduler, or ...
  - [ ] or... receiving from each client by event
### Reports
- [ ] Create a Report Dashboard to show relevant graphs and reports in client side
- [ ] Create a Report Dashboard to show relevant graphs and reports in main database

Suggestions and guidelines?

WIP in [ThinkOpen Solutions](https://github.com/thinkopensolutions/odoo-saas-tools) fork...

**Comment by yelizariev** [comment]
Ok, thanks.

Just one note about statistics. It's designed in assumption that server is not allowed to send request to SaaS Portal, because if we have 100 servers, it could be not a good idea and send heavy requests to SaaS Portal. So, only SaaS Portal can decide when it's necessary to update statistics from SaaS Server.
As for now SaaS server collect information from Clients at the moment of request, but this behaviour could be changed

**Comment by yelizariev** [comment]
Also, you could  create WIP PR, so anyone can see what updates are coming
