### ISSUE TITLE
The purpose of saas_pricing

### ISSUE THREAD

**Issue by saltonmassally** [it-projects-llc/odoo-saas-tools#24]
@yelizariev I am yet to understand the purpose of saas_pricing; I am working on integrating accounting and invoicing with saas_portal and would like to base it off saas_pricing. Can you please explain the thought process behind this addon. thanks

**Comment by yelizariev** [comment]
forward question to @kaerdsar

**Comment by kaerdsar** [comment]
@tarzan0820: saas_pricing is about Stripe. When you create an account on SaaS and if you selected a plan with some cost you must pay something monthly. The idea is we use Stripe for clients can do the payments. Actually the current module is not so useful because it was done for specific environment. Anyway I think the idea of Stripe with SaaS is good, so some work must be done.

**Comment by saltonmassally** [comment]
Thanks for clarifying this... and I love the idea behind this maybe we might want to do the following:
have a base addon saas_payment that provides common payment infrastructure
rename saas_pricing to saas_payment_stripe.

@yelizariev  what are your thoughts on this?

**Comment by yelizariev** [comment]
@tarzan0820 that is right. We have to have separate module for stipe
