### ISSUE TITLE
Max Users can't be set

### ISSUE THREAD

**Issue by erkesado** [it-projects-llc/odoo-saas-tools#261]
When I try to set 'Max Users' and 'Backup DB', it give me the error - Transport agent has not been configured. I didn't execute saas.py. I configured the saas manually.

**Comment by iledarn** [comment]
@erkesado ,
It is because you are using saas_portal_backup module. By default it tries to backup on any modification. This is an option and you can uncheck it in saas->clients->[you client] form in Database Settings -> Backup on modify.
When you are changing number of users it automatically tries to backup with this option enabled.

From this point a command is sent to server to backup certain database.
Actual backup take place on the server. And on the server odoo database one of the following modules should be installed:
- saas_server_backup_s3
- saas_server_backup_ftp

**Comment by erkesado** [comment]
@iledarn,

Great. Thanks. It works :)
