### ISSUE TITLE
Async jobs 

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#64]
I'm going to add async jobs for database creation and server syncronysation. Odoo connector https://github.com/OCA/connector is the best tool to do it, but it force us to use agpl license

What are your thoughts?

As for me I agree to switch to agpl

**Comment by yelizariev** [comment]
#23 
@tarzan0820 @kaerdsar @dhbahr

**Comment by yelizariev** [comment]
@nicholas-itpedia

**Comment by saltonmassally** [comment]
@yelizariev will this also be used to configure databases? Especially taking into consideration the proposed change to configuring multiple clients at the same time, #59 

I can see the value in server sync but I don't really see why we would use async for database creation... what is your line of thoughts on this...

In terms of licensing I would confess that I do not have indepth knowledge of this and so will leave to you and the others, especially @nicholas-itpedia to weigh in on this... but from a layman's perspective I see no problem moving to AGPL

**Comment by yelizariev** [comment]
> will this also be used to configure databases?

yeah, it can be done too.

> I can see the value in server sync but I don't really see why we would use async for database creation... what is your line of thoughts on this...

My colleague is developing saas_portal_sale module to sale Subscription via website_sale module. It would add button "Try trial". After singing up user is redirected to special page, say /trial. Handler for this route has to reply quickly to show a message to client "You trial database is creating, you will get email with credentials shortly". But this handler has to start database creation process too. So, we need a async creation here. 
Also, it could be help for any kind mass database creation (e.g. we want to create trial database for 100 clients at once to send them a promotional emails).
Anyway, it would be optional, so you can create database async as well as in a usual sync way.

**Comment by saltonmassally** [comment]
@yelizariev Ha I understand... let me know how I can be of help

**Comment by yelizariev** [comment]
@tarzan0820 you can start work on database configuration wizard, as it's not in my near plans. I suggest to add a tick weither to use async configration.
You can use this module as example of usage OCA connector: https://github.com/OCA/connector-interfaces/tree/8.0/base_import_async

**Comment by saltonmassally** [comment]
@yelizariev no problem, lol @ how you like referring to checkboxes as ticks :)

**Comment by yelizariev** [comment]
I've learned word "tick" from UK guys)

**Comment by cmsalmeida** [comment]
what you decided about license?

**Comment by yelizariev** [comment]
I'll switch everything to AGPL

**Comment by nagalman** [comment]
I am sorry I missed the discussion on this topic.
If the Odoo module depends (as listed in the manifest) or a Python source file in the module uses code licensed by the AGPL license, then the Odoo module MUST be AGPL.

If the AGPL code you are using depends on or uses code for LGPL, then the LGPL code can stay LGPL. Custom code in this project that is LGPL can stay LGPL as long as it does not depend or use AGPL code.

LGPL is better because it is a very copyleft license (derivatives have the same requirement), but it works with code from any license, including AGPL code. So if future software engineers want to use AGPL, GPL, LGPL, Apache, Mozilla, BSD, EULA, etc, they have the OPTION to do so. Keeping as much code as possible LGPL actually increases choice and software engineer control over license type. If ALL of the source is changed to AGPL, then this will mandate that all future development effort be released under AGPL and some software engineers may not want to use the AGPL license.

I recommend changing the license of the source to AGPL that is required to be AGPL because it depends or uses AGPL code, and keep the code that is not effected as LGPL.

**Comment by nicholas-itpedia** [comment]
I am sorry I missed the discussion on this topic.

If the Odoo module depends (as listed in the manifest) or a Python source file in the module uses code licensed by the AGPL license, then the Odoo module MUST be AGPL.
If the AGPL code you are using depends on or uses code for LGPL, then the LGPL code can stay LGPL. Custom code in this project that is LGPL can stay LGPL as long as it does not depend or use AGPL code.

LGPL is better because it is a very copyleft license (derivatives have the same requirement), but it works with code from any license, including AGPL code. So if future software engineers want to use AGPL, GPL, LGPL, Apache, Mozilla, BSD, EULA, etc, they have the OPTION to do so. Keeping as much code as possible LGPL actually increases choice and software engineer control over license type. If ALL of the source is changed to AGPL, then this will mandate that all future development effort be released under AGPL and some software engineers may not want to use the AGPL license.

I recommend changing the license of the source to AGPL that is required to be AGPL because it depends or uses AGPL code, and keep the code that is not affected as LGPL.

**Comment by yelizariev** [comment]
Thank you @nicholas-itpedia 
I think we can add new modules (for async jobs) which would be  depend on AGPL modules (oca connectors) and make such modules AGPL and keep other on LGPL\GPL

**Comment by yelizariev** [comment]
I close this issue as no permission from other developers is required anymore. For related questions new issue can be created
